In [1]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv('MyFoodRatings.csv',encoding="ISO-8859-1")

In [8]:
data.drop('Name',axis=1,inplace=True)

In [41]:
data.shape

(12, 9)

In [19]:
u, s, vt =np.linalg.svd(data,full_matrices=True)

In [20]:
print("U: ", u.shape, " VT: ", vt.shape)

U:  (12, 12)  VT:  (9, 9)


In [27]:
s

array([  1.27279221e+01,   1.05770379e+01,   8.84826058e+00,
         1.24205263e+00,   1.06125858e+00,   4.06927550e-01,
         5.43862610e-16,   3.23597471e-16,   2.65957113e-32])

In [30]:
np.set_printoptions(precision=2,threshold=10000)

In [36]:
print(s[0])

12.7279220614


In [38]:
np.diag(s[:3])

array([[ 12.73,   0.  ,   0.  ],
       [  0.  ,  10.58,   0.  ],
       [  0.  ,   0.  ,   8.85]])

In [46]:
pd.DataFrame(vt).head(3)

0        1        2         3         4         5         6  \
0 -0.57735 -0.57735 -0.57735  0.000000  0.000000  0.000000  0.000000   
1  0.00000  0.00000  0.00000 -0.637875 -0.512261 -0.575068  0.000000   
2  0.00000  0.00000  0.00000  0.000000  0.000000  0.000000 -0.476163   

          7         8  
0  0.000000  0.000000  
1  0.000000  0.000000  
2 -0.557638 -0.679933

In [47]:
fdata=pd.read_csv('FoodRatings_all_same_5.csv')

In [49]:
fdata.drop('Name',axis=1,inplace=True)

In [50]:
u,s,vt=np.linalg.svd(fdata)

In [51]:
fdata

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         5       5       5         0            0     0      0      0   
2         5       5       5         0            0     0      0      0   
3         5       5       5         0            0     0      0      0   
4         0       0       0         5            5     5      0      0   
5         0       0       0         5            5     5      0      0   
6         0       0       0         5            5     5      0      0   
7         0       0       0         5            5     5      0      0   
8         0       0       0         0            0     0      5      5   
9         0       0       0         0            0     0      5      5   
10        0       0       0         0            0     0      5      5   
11        0       0       0         0            0     0      5      5   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         5  
9         5  
10        5  
11        5

In [54]:
s

array([  1.73e+01,   1.73e+01,   1.73e+01,   3.93e-16,   2.80e-49,
         0.00e+00,   0.00e+00,   0.00e+00,   0.00e+00])

In [57]:
frdata=pd.read_csv('FoodRatings_all_same_5_4_3.csv')
frdata.drop('Name',axis=1,inplace=True)

In [58]:
frdata.head()

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  Tempura
0        5       5       5         0            0     0      0      0        0
1        5       5       5         0            0     0      0      0        0
2        5       5       5         0            0     0      0      0        0
3        5       5       5         0            0     0      0      0        0
4        0       0       0         4            4     4      0      0        0

In [59]:
u,s,vt=np.linalg.svd(frdata)

In [61]:
s[:3]

array([ 17.32,  13.86,  10.39])