# Numpy
## we are going to see some details around numpy and various python data structures
### Numpy array solve the scenario of doing calculations over entire arrays without explicit loopings

In [1]:
world={'afghanistan': 30.55, 'albania': 2.81,
'algeria': 39.21, 'sealand': 2.7e-05}
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

# BMI is calculate by dividing weight by height square
## traditional array doesn't support such operation
### (weight / height *height) :TypeError: unsupported operand type(s) for (**): 'list' and 'int'

In [2]:
import numpy as np
#print(weight/height*height)

#creating numpy array from python array
np_height=np.array(height)
np_weight=np.array(weight)
print(type(np_height)," ",type(np_weight))

#with numpy array we can do above operation over entire data series
bmi=np_weight/np_height**2
print(type(bmi))
print(bmi)

<class 'numpy.ndarray'>   <class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 21.85171573  20.97505669  21.75028214  24.7473475   21.44127836]


### list vs numpy array

In [3]:
#numpy array can only contains one type and operand behavior will differ from type to type
np_numarray=np.array([1,2,3,4])
np_textarray=np.array(("saurabh","jain"))
np_mixvar=np.array([1,True,"A"])
print(str(type(np_numarray))+" " + str(type(np_textarray))+" "+str(type(np_mixvar)))
print("np_numarray ", np_numarray)
print("np_mixvar ", np_mixvar)
print("np_textarray ", np_textarray)
print("-- Different behaviour depending on elements type--")
print(np_numarray+np_numarray)
#np_textarray+np_textarray
# ERROR: TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U7') dtype('<U7') dtype('<U7')
np_boolarr=np.array([True,False,True,False,False])
np_boolarr1=np.array([True,True,False,True,False])
np_boolarr
print(np_boolarr+np_boolarr)
print(np_boolarr+np_boolarr1)
print(np_boolarr&np_boolarr1)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
np_numarray  [1 2 3 4]
np_mixvar  ['1' 'True' 'A']
np_textarray  ['saurabh' 'jain']
-- Different behaviour depending on elements type--
[2 4 6 8]
[ True False  True False False]
[ True  True  True  True False]
[ True False False False False]


# Subsetting on numpy array

In [4]:
print(bmi)
print(bmi[1:4])
print(bmi>23)
print(bmi[bmi>23])

[ 21.85171573  20.97505669  21.75028214  24.7473475   21.44127836]
[ 20.97505669  21.75028214  24.7473475 ]
[False False False  True False]
[ 24.7473475]


# muliti dimension numpy array

In [5]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
[65.4, 59.2, 63.6, 88.4, 68.7]])

#subsetting
print(np_2d[0])
print(np_2d[0,2])
print(np_2d[0][2])
print(np_2d[0][1:3])
print(np_2d[:,1:3])
print(np_2d.shape)

[ 1.73  1.68  1.71  1.89  1.79]
1.71
1.71
[ 1.68  1.71]
[[  1.68   1.71]
 [ 59.2   63.6 ]]
(2, 5)


## some mathematical operation on numpy array

In [6]:
np_city=np.array([[ 1.64, 71.78],
[ 1.37, 63.35],
[ 1.6 , 55.09],
[ 2.04, 74.85],
[ 2.04, 68.72],
[ 2.01, 73.57]])
print(np_city.shape)

print("mean: ",np.mean(np_city[:,0]))
print("median: ",np.median(np_city[:,0]))
print("corrcoef: ",np.corrcoef(np_city[:,0],np_city[:,1]))
print("Standard deviation: ",np.std(np_city[:,0]))
print("Sum of column 1: ",np.sum(np_city[:,0]))
print("Sorted column one", np.sort(np_city))

dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41),('Lancelot', 1.9, 38),('Galahad', 1.7, 38)]
structured_arr = np.array(values, dtype=dtype)
print(structured_arr)
print(structured_arr.shape)
print(type(structured_arr))
print(structured_arr[0][0])
print(np.sort(structured_arr,order=['age','height']))

(6, 2)
mean:  1.78333333333
median:  1.825
corrcoef:  [[ 1.          0.64924262]
 [ 0.64924262  1.        ]]
Standard deviation:  0.260810701894
Sum of column 1:  10.7
Sorted column one [[  1.64  71.78]
 [  1.37  63.35]
 [  1.6   55.09]
 [  2.04  74.85]
 [  2.04  68.72]
 [  2.01  73.57]]
[(b'Arthur',  1.8, 41) (b'Lancelot',  1.9, 38) (b'Galahad',  1.7, 38)]
(3,)
<class 'numpy.ndarray'>
b'Arthur'
[(b'Galahad',  1.7, 38) (b'Lancelot',  1.9, 38) (b'Arthur',  1.8, 41)]


### generating sample data with numpy array

In [7]:
sample=np.round(np.random.normal(10,4,5000),2)
print(sample)

[ 14.44   8.04   0.19 ...,  14.91   3.45  10.84]


# Dataframe from Dictionary Pandas

In [8]:
dict = {
"country":["Brazil", "Russia", "India", "China", "South Africa"],
"capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
"area":[8.516, 17.10, 3.286, 9.597, 1.221],
"population":[200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics=pd.DataFrame(dict)

print(brics)

brics.index=['BR','RU','IN','CH','SA']
print(brics)

     area    capital       country  population
0   8.516   Brasilia        Brazil      200.40
1  17.100     Moscow        Russia      143.50
2   3.286  New Delhi         India     1252.00
3   9.597    Beijing         China     1357.00
4   1.221   Pretoria  South Africa       52.98
      area    capital       country  population
BR   8.516   Brasilia        Brazil      200.40
RU  17.100     Moscow        Russia      143.50
IN   3.286  New Delhi         India     1252.00
CH   9.597    Beijing         China     1357.00
SA   1.221   Pretoria  South Africa       52.98


In [10]:
#importing dataframe from csv
brics_csv=pd.read_csv("C:\Saurabh\Tutorials\DataScience\pandas_brics.csv")
print(brics_csv)

brics_csv=pd.read_csv("C:\Saurabh\Tutorials\DataScience\pandas_brics.csv",index_col=0)
print(brics_csv)

  Unnamed: 0       country    capital    area  population
0         BR        Brazil   Brasilia   8.516      200.40
1         RU        Russia     Moscow  17.100      143.50
2         IN         India  New Delhi   3.286     1252.00
3         CH         China    Beijing   9.597     1357.00
4         SA  South Africa   Pretoria   1.221       52.98
         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


In [11]:
#subsetting dataframe using pandas
# COLUMN ACCESS: [] -> Series [[ ]] -> DataFrame
print(type(brics['country']))
print(type(brics[['country']]))
print(brics[['country']])
print(brics[['country','capital']])

#ROW ACCESS of PANDAS DataFrame
print(brics[0:3])

#row and column filtering
print(brics[0:][['country','population']])
#brics[1,0] #ERROR
print(brics.loc[['RU','IN','CH'],['country','capital']]) #location based
print(brics.loc[:,['country','capital']])

print(brics.iloc[:,[1,2,3]])

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
         country
BR        Brazil
RU        Russia
IN         India
CH         China
SA  South Africa
         country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria
      area    capital country  population
BR   8.516   Brasilia  Brazil       200.4
RU  17.100     Moscow  Russia       143.5
IN   3.286  New Delhi   India      1252.0
         country  population
BR        Brazil      200.40
RU        Russia      143.50
IN         India     1252.00
CH         China     1357.00
SA  South Africa       52.98
   country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing
         country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria
      capital       country  population
BR   Brasilia     