# <font color='red'>Python </font>
## Important topics overview

##### enumerate

In [1]:
lst=[1,2,3,4,5]
for i,element in enumerate(lst):
    print(i, " : ",element)

0  :  1
1  :  2
2  :  3
3  :  4
4  :  5


#### List expression

In [2]:
# a simple way of iterating over the list
# default way

result=[]
for i in lst:
    result.append(i**2)
print(result) # [1, 4, 9, 16, 25]
# List Expression
result=[x**2 for x in lst]
print(result)

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]


#### Lambda 
 *an anonymous funciton*

In [3]:
ls=[1,2,3,4]
ls1=[4,3,2,1]
lambda x,y: x+y, ls,ls1 # (<function __main__.<lambda>(x, y)>, [1, 2, 3, 4], [4, 3, 2, 1])
fx=lambda x,y: x+y
list(map(fx,ls,ls1))

[5, 5, 5, 5]

#### map

In [4]:
10<9

False

In [5]:
greater=lambda x,y: (x,y)[x<y]

list(map(greater, [4],[9]))[0]

9

In [6]:
#count words starting with S using map
word_list=['San Jose', 'San Francisco', 'Santa Fe', 'Houston']

letterwithS=lambda x: x[0]=='S'

count=list(map(letterwithS,word_list)) # --> gives you a boolean list based on condition
print(count)

[True, True, True, False]


In [7]:
for i,v in enumerate(count):
    if v==True:
        print(word_list[i])

San Jose
San Francisco
Santa Fe


#### reduce

In [8]:
#it helps to do complex check on iterables reducing size. It keeps chaining last run result
from functools import reduce

msg_lst=['A','B','C','D','E']

reduce(lambda x,y: x+' '+y, msg_lst)

'A B C D E'

#### filter

In [9]:
list(filter(letterwithS,word_list)) # --> filter gives you a filtered list

['San Jose', 'San Francisco', 'Santa Fe']

### Recommended Additional Content
 - [Meand and Median: Basic](https://www.khanacademy.org/math/statistics-probability/displaying-describing-data/mean-median-basics/v/statistics-the-average)
 - [Mean and Median: Advanced](https://www.khanacademy.org/math/statistics-probability/displaying-describing-data/more-mean-median/e/calculating-the-mean-from-various-data-displays)
 - [Range, IQR, Mean absolute Deviation(MAD)](https://www.khanacademy.org/math/statistics-probability/displaying-describing-data/range-iqr-mad/v/range-and-mid-range)
 - [Population variance and standard deviation](https://www.khanacademy.org/math/statistics-probability/displaying-describing-data/pop-variance-standard-deviation/v/range-variance-and-standard-deviation-as-measures-of-dispersion)
 - [Sample variance and standard deviation](https://www.khanacademy.org/math/statistics-probability/displaying-describing-data/sample-standard-deviation/v/sample-variance)
 - [Basic probability](https://www.khanacademy.org/math/statistics-probability/probability-library)
 - [Random variables](https://www.khanacademy.org/math/statistics-probability/random-variables-stats-library)

# <font color='red'>Python Datascience Topics</font>
## General Overview

### A Data-structure in any programming language have certain attributes and operations associated with it.
***
Broadly some of these are listed below
<img src="E2E_overview.png" style="width: 600px;" alt="basic operations on datastructure" title="Common datastructure operations" />
***
> *Overview*
 - [numpy](#numpy)
     1. [attributes](#numpy-attributes)
     2. [features](#numpy-features)
     3. [operations](#numpy-operations)
 - [pandas](#pandas)
 - [Group by](#pandas-groupby)
 - [pivot-table](#pivot-table)
 - [crosstab](#crosstab)

***
> **MAIN MODULES**
1. [hypothetical-testing](#hypothetical-testing)

<a id='numpy'></a>
# Numpy : Overview

#### Enables to write vectorized code, convenient to read, write and concise
#### * Faster computation
#### * Stands for numerical Python
#### Lib written for scientific computation and data analysis
#### Basic object is ndarray, an array of n dimesional homogeneous (same data type) array

In [10]:
import numpy as np

<a id='numpy-attributes'></a>
## ATTRIBUTES

In [11]:
array_1d=np.array([1,2,3,4,5]) 
print(array_1d," : ", type(array_1d)) # [1 2 3 4 5]  :  <class 'numpy.ndarray'>
array_2d=np.array([['row-1',1,2],['row-2',3,4]])
print(array_2d, " : ",type(array_2d), " shape(dimension): ", array_2d.shape, " size(len): ", array_2d.size)

# [['row-1' '1' '2']
#  ['row-2' '3' '4']]  :  <class 'numpy.ndarray'>  shape(dimension):  (2, 3)  size(len):  6

[1 2 3 4 5]  :  <class 'numpy.ndarray'>
[['row-1' '1' '2']
 ['row-2' '3' '4']]  :  <class 'numpy.ndarray'>  shape(dimension):  (2, 3)  size(len):  6


##### Vectorized Coding

In [12]:
list1=[1,2,3,4]
list2=[8,7,6,5]

print("To add these two list (each items), we need to iterate and than add")
print(list(map(lambda x, y: x+y, list1,list2)))
       
    # [9, 9, 9, 9]
        
print("In vectorized form i.e. numpy it is simple, elegant code")

nparr1=np.array(list1)
nparr2=np.array(list2)
print(nparr1+nparr2)

    # [9 9 9 9]

To add these two list (each items), we need to iterate and than add
[9, 9, 9, 9]
In vectorized form i.e. numpy it is simple, elegant code
[9 9 9 9]


##### numpy arrray creation, initialization

In [13]:
tup1=(1,2,3,4)
print("from tuple: ",np.array(tup1))         # from tuple:  [1 2 3 4]
print("from list: ",np.array(list1))         # from list:  [1 2 3 4]

print("---- Default numpy array for data generation ----\n")
print("---- np.ones() ----\n")
print("dtype=str ", np.ones((2,3),dtype=np.str))
    # dtype=str  [['1' '1' '1']
    #  ['1' '1' '1']]
print("dtype=default i.e. float64", np.ones((2,3))," dtype: ",type(np.ones((2,3))[0][0]))
    # dtype=default i.e. float64 [[1. 1. 1.]
    #  [1. 1. 1.]]  dtype:  <class 'numpy.float64'>
    
print("\n---- np.zeros() ----\n")
print("dtype=default i.e. float64", np.zeros((2,3))," dtype: ",type(np.zeros((2,3))[0][0]))
    # dtype=default i.e. float64 [[0. 0. 0.]
    #  [0. 0. 0.]]  dtype:  <class 'numpy.float64'>
    
print("\n---- np.random.random() create array of random numbers between 0-1----\n")
# np.random.seed(4) # This will make sure same number generated on each run (see value)
print("dtype=default i.e. float64", np.random.random([2,3])," dtype: ",type(np.random.random((2,3))[0][0]))
    # dtype=default i.e. float64 [[0.28914631 0.50254531 0.46478469]
    #  [0.99434512 0.87326953 0.25146478]]  dtype:  <class 'numpy.float64'>
    
print("\n---- np.arange() creates an array of fix increment step----\n")
print("dtype=default i.e. float64", np.arange(10.0,100.0,15)," dtype: ",type(np.arange(10.0,100.0,5)[0]))
    #  [10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85. 90. 95.]  dtype:  <class 'numpy.float64'>

print("\n---- np.linspace() array of fix length between a range----\n")
print("dtype=default i.e. float", np.linspace(10,18,8)," dtype: ",type(np.linspace(10,18,8)[0]))

    #[10. 11.14285714 12.28571429 13.42857143 14.57142857 15.71428571 16.85714286 18.]  dtype:  <class 'numpy.float64'>

from tuple:  [1 2 3 4]
from list:  [1 2 3 4]
---- Default numpy array for data generation ----

---- np.ones() ----

dtype=str  [['1' '1' '1']
 ['1' '1' '1']]
dtype=default i.e. float64 [[1. 1. 1.]
 [1. 1. 1.]]  dtype:  <class 'numpy.float64'>

---- np.zeros() ----

dtype=default i.e. float64 [[0. 0. 0.]
 [0. 0. 0.]]  dtype:  <class 'numpy.float64'>

---- np.random.random() create array of random numbers between 0-1----

dtype=default i.e. float64 [[0.68411725 0.21291109 0.31680642]
 [0.70310226 0.02662171 0.42320984]]  dtype:  <class 'numpy.float64'>

---- np.arange() creates an array of fix increment step----

dtype=default i.e. float64 [10. 25. 40. 55. 70. 85.]  dtype:  <class 'numpy.float64'>

---- np.linspace() array of fix length between a range----

dtype=default i.e. float [10.         11.14285714 12.28571429 13.42857143 14.57142857 15.71428571
 16.85714286 18.        ]  dtype:  <class 'numpy.float64'>


<a id='numpy-features'></a>
## FEATURES
##### Inspect the Structure and Content of Arrays

* `shape`: Shape of array (n x m)
* ```dtype```: data type (int, float etc.)
* ```ndim```: Number of dimensions (or axes)
* ```itemsize```: Memory used by each array elememnt in bytes

In [14]:
np_arr=np.random.random((2,3))
print(np_arr.size) # 6 i.e. 2*3
print(np_arr)
print(np_arr[0]) # 0.001544449651610158
 
np_arr3d=np.random.random((2,3,4))  # read from right to left (for any array higher than 2 dimensions)
    # for example (2,3,4) will have 4 elements(columns) 3 rows and 2 of thema
    # [[[0.20285425 0.16040217 0.72273091 0.8505519 ]
    #   [0.70323723 0.18269224 0.0398234  0.60145375]
    #   [0.07136791 0.29464647 0.19020854 0.31875633]]

    #  [[0.75006555 0.77085525 0.19401341 0.82424295]
    #   [0.23649788 0.90376864 0.29167265 0.55492356]
    #   [0.28163111 0.6677762  0.56934992 0.48377137]]]

print(" number of dimension i.e. 2D Array :",np_arr.ndim) #  number of dimension i.e. 2D Array : 2  
print(" number of dimension i.e. 3D Array :",np_arr3d.ndim) #  number of dimension i.e. 3D Array : 3

print("Shape of array i.e. rows, columns: ",np_arr3d.shape) # Shape of array i.e. rows, columns:  (2, 3, 4)

arr_str=np.array(np.random.random((2,3)),dtype=np.str)
arr_float=np.array(np.random.random((2,3)),dtype=np.float64)
print("String: Memory size of each element (bytes): ",arr_str.itemsize) # String: Memory size of each element (bytes):  128
print("String: Memory size of each element (bytes): ",arr_float.itemsize) # String: Memory size of each element (bytes):  8

6
[[0.84711064 0.77431953 0.63871027]
 [0.99016125 0.70636261 0.27212406]]
[0.84711064 0.77431953 0.63871027]
 number of dimension i.e. 2D Array : 2
 number of dimension i.e. 3D Array : 3
Shape of array i.e. rows, columns:  (2, 3, 4)
String: Memory size of each element (bytes):  128
String: Memory size of each element (bytes):  8


##### Slcing, subset and extraction

In [15]:
nparr1=np.array(list(set(np.append(nparr1,nparr2))))
print((nparr1))                                                #[1 2 3 4 5 6 7 8]
print("------------Slicing----------------")
print("All [:] " ,nparr1[:])                                   # All [:]  [1 2 3 4 5 6 7 8]
print("start -> last [1:] " ,nparr1[1:])                       #start -> last [1:]  [2 3 4 5 6 7 8]
print("0 till end(excluding 2) [:2] " ,nparr1[:2])             # 0 till end(excluding 2) [:2]  [1 2]
print("\n------------subset----------------")
print("subsets [[a,b,c]] " ,nparr1[[1,3,4]])                   # subsets [[a,b,c]]  [2 4 5]
print("stepping [1:,:,2] " ,nparr1[1::2])                      # stepping [1:,:,2]  [2 4 6 8]
print("\n------------Multidimensional----------------\n")
print("\n------------Slicing----------------\n")
print("All [:] " ,np_arr3d[:]) 
                                                            #   All [:]  [[[0.83928841 0.17334502 0.27827657 0.48414788]
                                                            #   [0.85987119 0.11521202 0.33868847 0.53224018]
                                                            #   [0.67834956 0.10519407 0.75528363 0.5569211 ]]

                                                            #  [[0.5171444  0.38087046 0.31464712 0.89050462]
                                                            #   [0.99377647 0.17521486 0.21150118 0.66703409]
                                                            #   [0.7645629  0.82296581 0.30244554 0.20910031]]]
print("\nSubsetting [1:2,:,2:3] " ,np_arr3d[1:2,:,2:3])
                                                            # Subsetting [1:2,:,2:3]  [[[0.31464712]
                                                            #   [0.21150118]
                                                            #   [0.30244554]]]

[1 2 3 4 5 6 7 8]
------------Slicing----------------
All [:]  [1 2 3 4 5 6 7 8]
start -> last [1:]  [2 3 4 5 6 7 8]
0 till end(excluding 2) [:2]  [1 2]

------------subset----------------
subsets [[a,b,c]]  [2 4 5]
stepping [1:,:,2]  [2 4 6 8]

------------Multidimensional----------------


------------Slicing----------------

All [:]  [[[0.57315038 0.89636181 0.60155809 0.55072991]
  [0.33724044 0.76101421 0.09050304 0.01169044]
  [0.45358563 0.21953825 0.6273078  0.48120555]]

 [[0.77166384 0.0517012  0.9371502  0.16790192]
  [0.11551601 0.73703152 0.63776782 0.26374853]
  [0.24170483 0.78345576 0.39619883 0.86070269]]]

Subsetting [1:2,:,2:3]  [[[0.9371502 ]
  [0.63776782]
  [0.39619883]]]


In [16]:
print("------------Iteration----------------")
for i in np_arr3d:
    for j in i:
        for k in j:
            print(k)

------------Iteration----------------
0.5731503752091589
0.8963618079739508
0.6015580877821476
0.5507299077981526
0.33724043852224683
0.7610142096209015
0.09050304331929404
0.01169043786317292
0.45358562971548966
0.2195382529248423
0.6273077971967096
0.4812055475287069
0.7716638439486612
0.051701198782441615
0.9371502024392213
0.167901923253179
0.11551601104696585
0.737031522545405
0.6377678239109854
0.2637485346140135
0.24170483498852835
0.7834557636532072
0.396198833643304
0.8607026873408895


In [17]:
# Computation Speed
import time
import numpy as np
lst1=[i for i in range(1000000)]
lst2=[j**2 for j in range(1000000)]

t0=time.time()
product_lst=list(map(lambda x,y: x*y, lst1,lst2))
t1=time.time()
print(t1-t0) # 0.1715998649597168

np_ar1=np.array(lst1)
np_ar2=np.array(lst2)
t0=time.time()
product_arr=np_ar1*np_ar2
t1=time.time()
print(t1-t0) # 0.0

0.15600013732910156
0.0


<a id='numpy-operations'></a>
## OPERATIONS
The learning objectives of this section are:

* Manipulate arrays
    * Reshape arrays
    * Stack arrays
* Perform operations on arrays
    * Perform basic mathematical operations
    * Apply built-in functions 
    * Apply your own functions 
    * Apply basic linear algebra operations 


In [18]:
some_arr=np.arange(0,12).reshape(3,4).reshape(2,-1)
print('RESHAPING\n')
print(some_arr) #-1 implies the calculation will be done automatically
    # [[ 0  1  2  3  4  5]
    #  [ 6  7  8  9 10 11]]
print(some_arr.T)
    # [[ 0  6]
    #  [ 1  7]
    #  [ 2  8]
    #  [ 3  9]
    #  [ 4 10]
    #  [ 5 11]]
    
print("\n\nSTACKING -hstack, -vstack\n")
# Vertical stacking not possible if col numbers differ and for hstack rows should be same
# Error : ValueError: all the input array dimensions except for the concatenation axis must match exactly

ar1=np.arange(12).reshape(4,3)
ar2=np.arange(20).reshape(4,5)
print(ar1)
print(ar2)
    # [ 0  1  2]
    #  [ 3  4  5]
    #  [ 6  7  8]
    #  [ 9 10 11]] 

    # [[ 0  1  2  3  4]
    #  [ 5  6  7  8  9]
    #  [10 11 12 13 14]
    #  [15 16 17 18 19]]

print("Horizontal Stacking\n",np.hstack((ar1,ar2)))
    # [[ 0  1  2  0  1  2  3  4]
    #  [ 3  4  5  5  6  7  8  9]
    #  [ 6  7  8 10 11 12 13 14]
    #  [ 9 10 11 15 16 17 18 19]]
print("Vertical Stacking\n",np.vstack((ar1.reshape(3,4),ar2.reshape(5,4))))
    # [[ 0  1  2  3]
    #  [ 4  5  6  7]
    #  [ 8  9 10 11]
    #  [ 0  1  2  3]
    #  [ 4  5  6  7]
    #  [ 8  9 10 11]
    #  [12 13 14 15]
    #  [16 17 18 19]]

RESHAPING

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


STACKING -hstack, -vstack

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Horizontal Stacking
 [[ 0  1  2  0  1  2  3  4]
 [ 3  4  5  5  6  7  8  9]
 [ 6  7  8 10 11 12 13 14]
 [ 9 10 11 15 16 17 18 19]]
Vertical Stacking
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [19]:
#non numpy way of implementation is using the list expression whereas numpy way is to vectorize the function and apply
lst=np.arange(5)
print(lst)
t_list_lsx=[x/(x+1) for x in lst]
print(t_list_lsx) # [0.0, 0.5, 0.6666666666666666, 0.75, 0.8]

# VECTORIZE
n_list_v=np.vectorize(lambda x: x/(1+x))
print(n_list_v(lst)) # [0.         0.5        0.66666667 0.75       0.8       ]

[0 1 2 3 4]
[0.0, 0.5, 0.6666666666666666, 0.75, 0.8]
[0.         0.5        0.66666667 0.75       0.8       ]


In [20]:
matrx=np.arange(1,10,1,dtype=np.int).reshape(3,3)
matrx_c=matrx
print("Matrix\n",matrx)
print("Inverse Matrix\n",np.linalg.inv(matrx))
print("Determinant\n",np.linalg.det(matrx))
print("Eignen values and vectors\n",np.linalg.eig(matrx))

Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Inverse Matrix
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Determinant
 -9.51619735392994e-16
Eignen values and vectors
 (array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [21]:
matrx_c=np.arange(1,17,1,dtype=np.int).reshape(4,4)
    # [[ 1  2  3  4]
    #  [ 5  6  7  8]
    #  [ 9 10 11 12]
    #  [13 14 15 16]]

np.vsplit(matrx_c,2)[0][0,0:3]
m1=np.array([[1,2],[1,2]])
m2=np.array([[2,3],[2,3]])
print(m1, ":", m2)
np.dot(m1,m2)

[[1 2]
 [1 2]] : [[2 3]
 [2 3]]


array([[6, 9],
       [6, 9]])

## `Numpy Ends`

<a id='pandas'></a>
# `Pandas`

#### In this section, you will study:
1. The pandas Series (similar to a numpy array)
    * Creating a pandas series
    * Indexing series
2. Dataframes 
    * Creating dataframes from dictionaries
    * Importing CSV data files as pandas dataframes
    * Reading and summarising dataframes
    * Sorting dataframes

## `SERIES`
### 1. The Pandas Series 

A series is similar to a 1-D numpy array, and contains scalar values of the same type (numeric, character, datetime etc.). 
A dataframe is simply a table where each column is a pandas series.

In [22]:
import pandas as pd
s=pd.Series([1.0,2,4,5,'6'])
print("Data-type {} series".format(type(s))) #default type of each element may differ it doesn't restrict as numpy array
char_series=pd.Series(['a','b','3'])
print(char_series)

date_series=pd.date_range(start='11-09-2017', end='11-12-2017')
print("Series: {} Type: {} ".format(date_series,type(date_series)))
    # DatetimeIndex(['2017-11-09', '2017-11-10', '2017-11-11', '2017-11-12'], dtype='datetime64[ns]', freq='D') 
    # Type: <class 'pandas.core.indexes.datetimes.DatetimeIndex'> 

Data-type <class 'pandas.core.series.Series'> series
0    a
1    b
2    3
dtype: object
Series: DatetimeIndex(['2017-11-09', '2017-11-10', '2017-11-11', '2017-11-12'], dtype='datetime64[ns]', freq='D') Type: <class 'pandas.core.indexes.datetimes.DatetimeIndex'> 


In [23]:
# Indexing of series
    # [1.0,2,4,5,'6'] 
print(s[2]) # 4
print(s[:3])
    # 0    1
    # 1    2
    # 2    4
print(s[[0,2,3]])
    # 0    1
    # 2    4
    # 3    5

4
0    1
1    2
2    4
dtype: object
0    1
2    4
3    5
dtype: object


### `SERIES ENDS`

### `DATAFRAME`

In [24]:
# keys become column names
df = pd.DataFrame({'name': ['Vinay', 'Kushal', 'Aman', 'Saif'], 
                   'age': [22, 25, 24, 28], 
                    'occupation': ['engineer', 'doctor', 'data analyst', 'teacher']})

print(df.head())
                                                                        #    age    name    occupation
                                                                        # 0   22   Vinay      engineer
                                                                        # 1   25  Kushal        doctor
                                                                        # 2   24    Aman  data analyst
                                                                        # 3   28    Saif       teacher
market=pd.read_csv('./pandas/market_fact.csv',encoding='iso-8859-1')
print(market.head())
#      Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin 
# 0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   -30.51           3.60                 0.56  
# 1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13     4.56           0.93                 0.54  
# 2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26  1148.90           2.50                 0.59  
# 3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   729.34          14.30                 0.37  
# 4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35  1219.87          26.30                 0.38 

   age    name    occupation
0   22   Vinay      engineer
1   25  Kushal        doctor
2   24    Aman  data analyst
3   28    Saif       teacher
     Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38  


In [25]:
market.set_index('Ord_id',inplace=True)
#market.reset_index(inplace=True)
market.head(2)
#  	Prod_id 	Ship_id 	Cust_id 	Sales 	Discount 	Order_Quantity 	Profit 	Shipping_Cost 	Product_Base_Margin
# Ord_id 									
# Ord_5446 	Prod_16 	SHP_7609 	Cust_1818 	136.81 	0.01 	23 	-30.51 	3.60 	0.56
# Ord_5406 	Prod_13 	SHP_7549 	Cust_1818 	42.27 	0.01 	13 	4.56 	0.93 	0.54

Prod_id   Ship_id    Cust_id   Sales  Discount  Order_Quantity  \
Ord_id                                                                     
Ord_5446  Prod_16  SHP_7609  Cust_1818  136.81      0.01              23   
Ord_5406  Prod_13  SHP_7549  Cust_1818   42.27      0.01              13   

          Profit  Shipping_Cost  Product_Base_Margin  
Ord_id                                                
Ord_5446  -30.51           3.60                 0.56  
Ord_5406    4.56           0.93                 0.54

In [26]:
print(market.sort_values(by='Prod_id',ascending=True).head(2))
print(market.sort_values(by=['Prod_id','Cust_id'],ascending=True).head(2))
market.sort_index(axis=0,ascending=False).head() # axis=1 sort rows containing columns name axis=0 wil sort column index

         Prod_id   Ship_id   Cust_id    Sales  Discount  Order_Quantity  \
Ord_id                                                                    
Ord_1067  Prod_1  SHP_1474  Cust_397  7333.45      0.07              27   
Ord_1791  Prod_1  SHP_2482  Cust_838   416.40      0.02              24   

          Profit  Shipping_Cost  Product_Base_Margin  
Ord_id                                                
Ord_1067 -207.28          35.00                 0.80  
Ord_1791   24.33           4.96                 0.58  
        Prod_id  Ship_id   Cust_id   Sales  Discount  Order_Quantity  Profit  \
Ord_id                                                                         
Ord_1    Prod_1    SHP_1    Cust_1  261.54      0.04               6 -213.25   
Ord_247  Prod_1  SHP_342  Cust_100  120.03      0.02               7  -56.06   

         Shipping_Cost  Product_Base_Margin  
Ord_id                                       
Ord_1            35.00                  0.8  
Ord_247          11.

Prod_id   Ship_id   Cust_id     Sales  Discount  Order_Quantity  \
Ord_id                                                                     
Ord_999  Prod_15  SHP_1383  Cust_361   5661.08      0.00              33   
Ord_998   Prod_8  SHP_1380  Cust_372    750.66      0.00              33   
Ord_998   Prod_5  SHP_1382  Cust_372   2149.37      0.03              42   
Ord_998   Prod_8  SHP_1381  Cust_372    254.32      0.01               8   
Ord_997  Prod_14  SHP_1379  Cust_365  28761.52      0.04               8   

          Profit  Shipping_Cost  Product_Base_Margin  
Ord_id                                                
Ord_999  1055.47          30.00                 0.62  
Ord_998   120.05           4.00                 0.60  
Ord_998   217.87          19.99                 0.55  
Ord_998  -117.39           6.50                 0.79  
Ord_997   285.11          24.49                 0.37

In [27]:
print(market[1::2].head())
market[['Sales','Ship_id']].head()
market.describe(include='all')

          Prod_id   Ship_id    Cust_id      Sales  Discount  Order_Quantity  \
Ord_id                                                                        
Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01              13   
Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09              43   
Ord_5446   Prod_6  SHP_7608  Cust_1818   164.0200      0.03              23   
Ord_4725   Prod_4  SHP_6593  Cust_1641  3410.1575      0.10              48   
Ord_4725   Prod_6  SHP_6593  Cust_1641    57.2200      0.07               8   

           Profit  Shipping_Cost  Product_Base_Margin  
Ord_id                                                 
Ord_5406     4.56           0.93                 0.54  
Ord_5456   729.34          14.30                 0.37  
Ord_5446   -47.64           6.15                 0.37  
Ord_4725  1137.91           0.99                 0.55  
Ord_4725   -27.72           6.60                 0.37  


Prod_id   Ship_id    Cust_id         Sales     Discount  \
count     8399      8399       8399   8399.000000  8399.000000   
unique      17      7701       1832           NaN          NaN   
top     Prod_6  SHP_1378  Cust_1140           NaN          NaN   
freq      1225         4         30           NaN          NaN   
mean       NaN       NaN        NaN   1775.878179     0.049671   
std        NaN       NaN        NaN   3585.050525     0.031823   
min        NaN       NaN        NaN      2.240000     0.000000   
25%        NaN       NaN        NaN    143.195000     0.020000   
50%        NaN       NaN        NaN    449.420000     0.050000   
75%        NaN       NaN        NaN   1709.320000     0.080000   
max        NaN       NaN        NaN  89061.050000     0.250000   

        Order_Quantity        Profit  Shipping_Cost  Product_Base_Margin  
count      8399.000000   8399.000000    8399.000000          8336.000000  
unique             NaN           NaN            NaN                  NaN  
top                NaN           NaN            NaN                  NaN  
freq               NaN           NaN            NaN                  NaN  
mean         25.571735    181.184424      12.838557             0.512513  
std          14.481071   1196.653371      17.264052             0.135589  
min           1.000000 -14140.700000       0.490000             0.350000  
25%          13.000000    -83.315000       3.300000             0.380000  
50%          26.000000     -1.500000       6.070000             0.520000  
75%          38.000000    162.750000      13.990000             0.590000  
max          50.000000  27220.690000     164.730000             0.850000

In [28]:
df.iloc[[True, True, False]] # applies to rows and assume all columns

age    name occupation
0   22   Vinay   engineer
1   25  Kushal     doctor

In [29]:
df.loc[:,[True, False, True]] # applied to columns

age    occupation
0   22      engineer
1   25        doctor
2   24  data analyst
3   28       teacher

In [30]:
df.loc[(df.age>24) & (df.occupation.isin(['doctor','engineer']))]

#df.occupation.isin(['doctor','engineer']) == (df.occupation.apply(lambda x: x in ['doctor','engineer']))]

age    name occupation
1   25  Kushal     doctor

In [31]:
#df.append(pd.DataFrame({'age':28,'name':'Saurabh','occupation':'doctor'}))
df=df.append(pd.DataFrame({'age':[28],'name':['Saurabh'],'occupation':['doctor']}))

In [32]:
df.occupation.is_unique

False

In [33]:
mer_df1=pd.DataFrame({
    'id':np.arange(0,10),
    'cust_key':np.linspace(1000,2000,10,dtype=np.int32)
})
mer_df2=pd.DataFrame({
    'cust_id':np.arange(0,10),
    'age':np.linspace(20,50,10,dtype=np.int32)
})

In [34]:
merged_on_diff_col=pd.merge(mer_df1,mer_df2,how='inner',left_on='id',right_on='cust_id')
merged_on_diff_col.head()

cust_key  id  age  cust_id
0      1000   0   20        0
1      1111   1   23        1
2      1222   2   26        2
3      1333   3   30        3
4      1444   4   33        4

In [35]:
mer_df1=pd.DataFrame({
    'id':np.arange(0,20,2),
    'cust_key':np.linspace(1000,2000,10,dtype=np.int32)
})
mer_df2=pd.DataFrame({
    'id':np.arange(0,10),
    'age':np.linspace(20,50,10,dtype=np.int32)
})

In [36]:
print(mer_df1.head())
mer_df2.head()

   cust_key  id
0      1000   0
1      1111   2
2      1222   4
3      1333   6
4      1444   8


age  id
0   20   0
1   23   1
2   26   2
3   30   3
4   33   4

In [37]:
pd.merge(mer_df1,mer_df2,on='id',how='left')

cust_key  id   age
0      1000   0  20.0
1      1111   2  26.0
2      1222   4  33.0
3      1333   6  40.0
4      1444   8  46.0
5      1555  10   NaN
6      1666  12   NaN
7      1777  14   NaN
8      1888  16   NaN
9      2000  18   NaN

In [38]:
mer_df2=pd.DataFrame({
    'id':[0,1,3,5,7,9,11,12,13,14],
    'age':np.linspace(20,50,10,dtype=np.int32)
})

In [39]:
pd.merge(mer_df1,mer_df2,on='id',how='right')

cust_key  id  age
0    1000.0   0   20
1    1666.0  12   43
2    1777.0  14   50
3       NaN   1   23
4       NaN   3   26
5       NaN   5   30
6       NaN   7   33
7       NaN   9   36
8       NaN  11   40
9       NaN  13   46

In [40]:
outer_df=pd.merge(mer_df1,mer_df2,on='id',how='outer')
outer_df

cust_key  id   age
0     1000.0   0  20.0
1     1111.0   2   NaN
2     1222.0   4   NaN
3     1333.0   6   NaN
4     1444.0   8   NaN
5     1555.0  10   NaN
6     1666.0  12  43.0
7     1777.0  14  50.0
8     1888.0  16   NaN
9     2000.0  18   NaN
10       NaN   1  23.0
11       NaN   3  26.0
12       NaN   5  30.0
13       NaN   7  33.0
14       NaN   9  36.0
15       NaN  11  40.0
16       NaN  13  46.0

### `DATAFRAME ENDS`

<a id='pandas-groupby'></a>
#### Aggregation and group operation

In [41]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
         'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
         'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
         'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
         'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df.head()

Points  Rank    Team  Year
0     876     1  Riders  2014
1     789     2  Riders  2015
2     863     2  Devils  2014
3     673     3  Devils  2015
4     741     3   Kings  2014

In [42]:
df.groupby('Team').groups #groupping by column Team

{'Devils': Int64Index([2, 3], dtype='int64'),
 'Kings': Int64Index([4, 6, 7], dtype='int64'),
 'Riders': Int64Index([0, 1, 8, 11], dtype='int64'),
 'Royals': Int64Index([9, 10], dtype='int64'),
 'kings': Int64Index([5], dtype='int64')}

In [43]:
df.groupby(['Team','Rank']).groups #grouping by 2-col first by Team and then by Rank

{('Devils', 2): Int64Index([2], dtype='int64'),
 ('Devils', 3): Int64Index([3], dtype='int64'),
 ('Kings', 1): Int64Index([6, 7], dtype='int64'),
 ('Kings', 3): Int64Index([4], dtype='int64'),
 ('Riders', 1): Int64Index([0], dtype='int64'),
 ('Riders', 2): Int64Index([1, 8, 11], dtype='int64'),
 ('Royals', 1): Int64Index([10], dtype='int64'),
 ('Royals', 4): Int64Index([9], dtype='int64'),
 ('kings', 4): Int64Index([5], dtype='int64')}

In [44]:
df_group_by_obj=df.groupby('Year')
for group_name,group_df in df_group_by_obj:
    print(group_name,"\n",group_df)

2014 
    Points  Rank    Team  Year
0     876     1  Riders  2014
2     863     2  Devils  2014
4     741     3   Kings  2014
9     701     4  Royals  2014
2015 
     Points  Rank    Team  Year
1      789     2  Riders  2015
3      673     3  Devils  2015
5      812     4   kings  2015
10     804     1  Royals  2015
2016 
    Points  Rank    Team  Year
6     756     1   Kings  2016
8     694     2  Riders  2016
2017 
     Points  Rank    Team  Year
7      788     1   Kings  2017
11     690     2  Riders  2017


In [45]:
df_group_by_obj.agg(np.size) # To find how many elements are there in each group applying np.size method on each series

Points  Rank  Team
Year                    
2014       4     4     4
2015       4     4     4
2016       2     2     2
2017       2     2     2

In [46]:
df_group_by_obj['Points','Rank'].agg([np.mean,np.sum]) # applying more than one function on groupped df's

Points       Rank    
        mean   sum mean sum
Year                       
2014  795.25  3181  2.5  10
2015  769.50  3078  2.5  10
2016  725.00  1450  1.5   3
2017  739.00  1478  1.5   3

In [47]:
print(df_group_by_obj.get_group(2014)) #To get specific groups
print(df_group_by_obj.corr())

   Points  Rank    Team  Year
0     876     1  Riders  2014
2     863     2  Devils  2014
4     741     3   Kings  2014
9     701     4  Royals  2014
               Points      Rank
Year                           
2014 Points  1.000000 -0.955264
     Rank   -0.955264  1.000000
2015 Points  1.000000 -0.182625
     Rank   -0.182625  1.000000
2016 Points  1.000000 -1.000000
     Rank   -1.000000  1.000000
2017 Points  1.000000 -1.000000
     Rank   -1.000000  1.000000


In [48]:
df_group_by_obj['Points','Rank'].boxplot()

2014         AxesSubplot(0.1,0.559091;0.363636x0.340909)
2015    AxesSubplot(0.536364,0.559091;0.363636x0.340909)
2016             AxesSubplot(0.1,0.15;0.363636x0.340909)
2017        AxesSubplot(0.536364,0.15;0.363636x0.340909)
dtype: object

In [49]:
df['Points Scaled']=df_group_by_obj.Points.transform(lambda x: ((x-x.mean())/x.std()) *100)

In [50]:
df_group_by_obj.get_group(2014)

Points  Rank    Team
0     876     1  Riders
2     863     2  Devils
4     741     3   Kings
9     701     4  Royals

In [51]:
df.groupby('Year',as_index=True).mean() ## Groupby is set as index disablinng it as_index=FALSE

Points  Rank  Points Scaled
Year                             
2014  795.25   2.5   3.552714e-15
2015  769.50   2.5   0.000000e+00
2016  725.00   1.5   0.000000e+00
2017  739.00   1.5   0.000000e+00

##### ````````GROUPBY ENDS````````

<a id='pivot-table'></a>
#### <font color='blue'>*PIVOT TABLE*</font>

In [52]:
def top(df, n=5, column='Points'):
    return df.sort_index(by=column)[-n:].drop(['Year','Team'],axis=1)

In [53]:
df.groupby(['Year','Team']).apply(top)

C:\ProgramData\Anaconda2\envs\DS_3_6\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  


Points  Rank  Points Scaled
Year Team                                  
2014 Devils 2      863     2      77.482564
     Kings  4      741     3     -62.043234
     Riders 0      876     1      92.350068
     Royals 9      701     4    -107.789398
2015 Devils 3      673     3    -148.379616
     Riders 1      789     2      29.983446
     Royals 10     804     1      53.047635
     kings  5      812     4      65.348535
2016 Kings  6      756     1      70.710678
     Riders 8      694     2     -70.710678
2017 Kings  7      788     1      70.710678
     Riders 11     690     2     -70.710678

In [54]:
df.groupby(['Year','Team']).apply(lambda x: x.head())

Points  Rank    Team  Year  Points Scaled
Year Team                                                
2014 Devils 2      863     2  Devils  2014      77.482564
     Kings  4      741     3   Kings  2014     -62.043234
     Riders 0      876     1  Riders  2014      92.350068
     Royals 9      701     4  Royals  2014    -107.789398
2015 Devils 3      673     3  Devils  2015    -148.379616
     Riders 1      789     2  Riders  2015      29.983446
     Royals 10     804     1  Royals  2015      53.047635
     kings  5      812     4   kings  2015      65.348535
2016 Kings  6      756     1   Kings  2016      70.710678
     Riders 8      694     2  Riders  2016     -70.710678
2017 Kings  7      788     1   Kings  2017      70.710678
     Riders 11     690     2  Riders  2017     -70.710678

In [55]:
df.pivot_table(index=['Year','Team'],values=['Points','Rank','Points Scaled'])


Points  Points Scaled  Rank
Year Team                               
2014 Devils     863      77.482564     2
     Kings      741     -62.043234     3
     Riders     876      92.350068     1
     Royals     701    -107.789398     4
2015 Devils     673    -148.379616     3
     Riders     789      29.983446     2
     Royals     804      53.047635     1
     kings      812      65.348535     4
2016 Kings      756      70.710678     1
     Riders     694     -70.710678     2
2017 Kings      788      70.710678     1
     Riders     690     -70.710678     2

In [56]:
df.pivot_table(index=['Year','Team'],values=['Points','Points Scaled'],columns='Rank',aggfunc='sum')

Points                      Points Scaled                         \
Rank             1      2      3      4             1          2           3   
Year Team                                                                      
2014 Devils    NaN  863.0    NaN    NaN           NaN  77.482564         NaN   
     Kings     NaN    NaN  741.0    NaN           NaN        NaN  -62.043234   
     Riders  876.0    NaN    NaN    NaN     92.350068        NaN         NaN   
     Royals    NaN    NaN    NaN  701.0           NaN        NaN         NaN   
2015 Devils    NaN    NaN  673.0    NaN           NaN        NaN -148.379616   
     Riders    NaN  789.0    NaN    NaN           NaN  29.983446         NaN   
     Royals  804.0    NaN    NaN    NaN     53.047635        NaN         NaN   
     kings     NaN    NaN    NaN  812.0           NaN        NaN         NaN   
2016 Kings   756.0    NaN    NaN    NaN     70.710678        NaN         NaN   
     Riders    NaN  694.0    NaN    NaN           NaN -70.710678         NaN   
2017 Kings   788.0    NaN    NaN    NaN     70.710678        NaN         NaN   
     Riders    NaN  690.0    NaN    NaN           NaN -70.710678         NaN   

                         
Rank                  4  
Year Team                
2014 Devils         NaN  
     Kings          NaN  
     Riders         NaN  
     Royals -107.789398  
2015 Devils         NaN  
     Riders         NaN  
     Royals         NaN  
     kings    65.348535  
2016 Kings          NaN  
     Riders         NaN  
2017 Kings          NaN  
     Riders         NaN

##### <font color='blue'>*Pivot Table Ends*</font>

<a id='crosstab'></a>
#### Crosstab

In [57]:
cross_tab_df=pd.crosstab(df.Team,df.Rank,margins=True)

In [58]:
cross_tab_df

Rank    1  2  3  4  All
Team                   
Devils  0  1  1  0    2
Kings   2  0  1  0    3
Riders  1  3  0  0    4
Royals  1  0  0  1    2
kings   0  0  0  1    1
All     4  4  2  2   12

In [59]:
cross_tab=cross_tab_df.reset_index()

In [60]:
cross_tab

Rank    Team  1  2  3  4  All
0     Devils  0  1  1  0    2
1      Kings  2  0  1  0    3
2     Riders  1  3  0  0    4
3     Royals  1  0  0  1    2
4      kings  0  0  0  1    1
5        All  4  4  2  2   12

In [61]:
cross_tab.index[[True, False, False, False, False, True]].tolist()
#(cross_tab['Team']=='All').tolist() ### TO GET Index based on some row condition

[0, 5]

In [62]:
cross_tab.drop(axis=1,index=cross_tab.index[cross_tab['Team']=='All'].tolist()) ### DROPPING ROW

Rank    Team  1  2  3  4  All
0     Devils  0  1  1  0    2
1      Kings  2  0  1  0    3
2     Riders  1  3  0  0    4
3     Royals  1  0  0  1    2
4      kings  0  0  0  1    1

##### <font color='black'>*Crosstab Ends*</font>

## `Pandas Ends` 

## `Getting and cleaning data`

#### *from Database*

In [85]:
import pymysql
conn=pymysql.connect(host="localhost",user="root",passwd="interOP@123",db="world")
c=conn.cursor()
c.execute('select * from city;')
all_rows=c.fetchall()
print(type(all_rows)) # All are tuples
db_df=pd.DataFrame(list(all_rows),columns=['ID','Name','Country','District','Population']) # Converting to dataframe

<class 'tuple'>


In [88]:
con2=pymysql.connect(host='localhost',db='world',user='root',passwd='interOP@123')
cur=conn.cursor()
cur.execute('select * from countrylanguage;')
rows=cur.fetchmany(20)
pd.DataFrame(list(rows),columns=['CountryCode','Language','Official','%age'])

CountryCode          Language Official  %age
0          ABW             Dutch        T   5.3
1          ABW           English        F   9.5
2          ABW        Papiamento        F  76.7
3          ABW           Spanish        F   7.4
4          AFG           Balochi        F   0.9
5          AFG              Dari        T  32.1
6          AFG            Pashto        T  52.4
7          AFG        Turkmenian        F   1.9
8          AFG             Uzbek        F   8.8
9          AGO              Ambo        F   2.4
10         AGO            Chokwe        F   4.2
11         AGO             Kongo        F  13.2
12         AGO           Luchazi        F   2.4
13         AGO  Luimbe-nganguela        F   5.4
14         AGO            Luvale        F   3.6
15         AGO            Mbundu        F  21.6
16         AGO   Nyaneka-nkhumbi        F   5.4
17         AGO         Ovimbundu        F  37.2
18         AIA           English        T   0.0
19         ALB         Albaniana        T  97.9

##### *Database ends*

##### *web* scrapping

In [94]:
import bs4, requests,pprint

In [109]:
url="https://play.google.com/store/apps/details?id=com.facebook.orca&hl=en&showAllReviews=true"
req=requests.get(url)
soup=bs4.BeautifulSoup(req.text,'html.parser')
#pprint.pprint(soup.select("<div jsname='lYU69'"))
pprint.pprint(soup.find("div", {"jsname": "fk8dgd"}))

None


##### *web ends*

##### *Write, read files*

In [129]:
with open('test.txt','w') as f:
    f.write("Simple, test, file\n also,this,new file \ntailing,to,end")
with open('test.txt','a') as f:
    f.write("New,test,file\nappended,to, file \n new, tailing, end")
with open(b'test.txt','r') as f:
    lines=f.readlines()
stripped=[x.rstrip('\n') for x in lines]
pd.DataFrame(stripped)

0
0           Simple, test, file
1          also,this,new file 
2  tailing,to,endNew,test,file
3           appended,to, file 
4            new, tailing, end

##### *Write, read files ends*

##### *reading csv files* 

In [142]:
import csv

In [143]:
with open(b'test.txt','r') as f:
    rows=csv.reader(f,delimiter=',')
    for r in rows:
        print(', '.join(r))

Simple,  test,  file
 also, this, new file 
tailing, to, endNew, test, file
appended, to,  file 
 new,  tailing,  end


##### *reading csv files -ends* 

In [147]:
add = pd.read_csv("./gettingdata/addresses.txt", sep="\t",header = None)

In [155]:
words=pd.read_csv('./gettingdata/header_file.csv',sep=',') #~~ pd.read_csv('./gettingdata/header_file.csv',sep=',',header=0)
words

Index Alphabet          Words
0      1        a     atrocities
1      2        b      ballistic
2      3        c       crwaling
3      4        d       decisive
4      5        e      empirical
5      6        f          faith
6      7        g            god
7      8        h           hope
8      9        i  indispensable
9     10        j       jeopardy

##### *PDF*

In [157]:
import PyPDF2

# reading the pdf file
pdf_object = open('./gettingdata/animal_farm.pdf', 'rb')
pdf_reader = PyPDF2.PdfFileReader(pdf_object)

# Number of pages in the PDF file
print(pdf_reader.numPages)

# get a certain page's text
page_object = pdf_reader.getPage(5)

# Extract text from the page_object
print(page_object.extractText())

55
Cowsandhorses,geeseandturkeys,
Allmusttoilforfreedom'ssake.
BeastsofEngland,beastsofIreland,
Beastsofeverylandandclime,
Hearkenwellandspreadmytidings
Ofthegoldenfuturetime.
Thesingingofthissongthrewtheanimalsintothewildestexcitement.
AlmostbeforeMajorhadreachedtheend,theyhadbegunsingingitforthem-
selves.Eventhestupidestofthemhadalreadypickedupthetuneandafewof
thewords,andasforthecleverones,suchasthepigsanddogs,theyhadthe
entiresongbyheartwithinafewminutes.Andthen,afterafewpreliminary
tries,thewholefarmburstoutinto
BeastsofEngland
intremendousunison.
Thecowslowedit,thedogswhinedit,thesheepbleatedit,thehorseswhinnied
it,theducksquackedit.Theyweresodelightedwiththesongthattheysang
itrightthroughetimesinsuccession,andmighthavecontinuedsingingitall
nightiftheyhadnotbeeninterrupted.
Unfortunately,theuproarawokeMr.Jones,whosprangoutofbed,making
surethattherewasafoxintheyard.Heseizedthegunwhichalwaysstoodina
cornerofhisbedroom,andletyachargeofnumber6shotintothedarkness.
Thepelletsburiedthem

##### *PDF -ends*

<a id='hypothetical-testing'></a>
## Hypothetical Testing
### Important library: ````scipy.stats````
   reference * http://hamelg.blogspot.com/2015/11/python-for-data-analysis-part-24.html

In [65]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import math

In [66]:
np.random.seed(6)

population_ages1 = stats.poisson.rvs(loc=18, mu=35, size=150000)
population_ages2 = stats.poisson.rvs(loc=18, mu=10, size=100000)
population_ages = np.concatenate((population_ages1, population_ages2))

minnesota_ages1 = stats.poisson.rvs(loc=18, mu=30, size=30)
minnesota_ages2 = stats.poisson.rvs(loc=18, mu=10, size=20)
minnesota_ages = np.concatenate((minnesota_ages1, minnesota_ages2))

print( population_ages.mean() )
print( minnesota_ages.mean() )

43.000112
39.26


In [67]:
type(population_ages)

numpy.ndarray

In [68]:
stats.ttest_1samp(a= minnesota_ages,               # Sample data
                 popmean= population_ages.mean())  # Pop mean

Ttest_1sampResult(statistic=-2.5742714883655027, pvalue=0.013118685425061678)

In [69]:
stats.t.cdf(-2.574271,df=49)*2 # as it is two tailed test

0.013118701690109116

 
    *If the t-statistic lies outside the quantiles of the t-distribution corresponding to our confidence level and degrees of freedom, we reject the null hypothesis. We can check the quantiles with stats.t.ppf():

    *We can calculate the chances of seeing a result as extreme as the one we observed (known as the p-value) by passing the t-statistic in as the quantile to the stats.t.cdf() function:

In [70]:
print(stats.t.ppf(q=0.025,  # Quantile to check
            df=49))  # Degrees of freedom
print(stats.t.ppf(q=0.975,  # Quantile to check
            df=49))  # Degrees of freedom

print("as p-value is less than confidence level i.e. 0.05) we reject null hypothesis :p-value",stats.t.cdf(x= -2.5742,      # T-test statistic
               df= 49) * 2 )  # Mupltiply by two for two tailed test*

-2.0095752344892093
2.009575234489209
as p-value is less than confidence level i.e. 0.05) we reject null hypothesis :p-value 0.013121066545690117


*Question: aplpha=.05, h0=35 h1!=35

In [71]:
commute_time=np.array([37,64,43,32,23,18,36,30,46,52,15,64,13,25,28,45,19,35,19,24,31,31,42,32,41,33,17,15,19,24,22,12])
print(len(commute_time))
print(stats.ttest_1samp(a=commute_time,popmean=35))
print("-----Fail to reject null hypothesis as p-value is > 0.05----")
stats.t.cdf(x=-1.7233,df=31)*2


32
Ttest_1sampResult(statistic=-1.7233018724723084, pvalue=0.09479631478752118)
-----Fail to reject null hypothesis as p-value is > 0.05----


0.09479665768152477

In [72]:
sigma = minnesota_ages.std()/math.sqrt(50)  # Sample stdev/sample size
print(sigma)
stats.t.interval(0.95,                        # Confidence level
                 df = 49,                     # Degrees of freedom
                 loc = minnesota_ages.mean(), # Sample mean
                 scale= sigma)                # Standard dev estimate

#REFERENCE https://www.google.com/search?client=firefox-b-ab&ei=rF2GW5DyDZX9rQGm1IHQCw&q=t-test+how+to+calculate+interval&oq=t-test+how+to+calculate+interval&gs_l=psy-ab.3..0i22i30k1l2.4968143.4973453.0.4973697.32.18.0.0.0.0.692.1823.0j1j4j5-1.6.0....0...1.1.64.psy-ab..26.6.1821...0j0i67k1.0.hCMVgAd8d9I#kpvalbx=1

1.4382795277692022


(36.369669080722176, 42.15033091927782)

#### Two sample T-Test ````stats.ttest_ind()  -->Independent

In [73]:
np.random.seed(12)
wisconsin_ages1 = stats.poisson.rvs(loc=18, mu=33, size=30)
wisconsin_ages2 = stats.poisson.rvs(loc=18, mu=13, size=20)
wisconsin_ages = np.concatenate((wisconsin_ages1, wisconsin_ages2))

print( wisconsin_ages.mean() )

42.8


In [74]:
stats.ttest_ind(a= minnesota_ages,
                b= wisconsin_ages,
                equal_var=False)    # Assume samples have equal variance?

Ttest_indResult(statistic=-1.7083870793286842, pvalue=0.09073104343957748)

#### Two sample T-Test Paired

In [75]:
np.random.seed(11)

before= stats.norm.rvs(scale=30, loc=250, size=100)

after = before + stats.norm.rvs(scale=5, loc=-1.25, size=100)

weight_df = pd.DataFrame({"weight_before":before,
                          "weight_after":after,
                          "weight_change":after-before})

weight_df.describe()             # Check a summary of the data

weight_after  weight_before  weight_change
count    100.000000     100.000000     100.000000
mean     249.115171     250.345546      -1.230375
std       28.422183      28.132539       4.783696
min      165.913930     170.400443     -11.495286
25%      229.148236     230.421042      -4.046211
50%      251.134089     250.830805      -1.413463
75%      268.927258     270.637145       1.738673
max      316.720357     314.700233       9.759282

In [76]:
stats.ttest_rel(a = before,
                b = after)

Ttest_relResult(statistic=2.5720175998568284, pvalue=0.011596444318439857)

In [77]:
print(stats.ttest_1samp(a=commute_time,popmean=35))
stats.t.cdf(x=-1.7233018724723084,df=31)*2 #cumulative distribution function x=statistic and df=degree of freedom N-1

Ttest_1sampResult(statistic=-1.7233018724723084, pvalue=0.09479631478752118)


0.09479631478752118

In [78]:
sigma=commute_time.std()/math.sqrt(32)
stats.t.interval(.95,
                df=31,
                scale=sigma,
                loc=35)

(30.158580295277904, 39.8414197047221)

####  *`Hypothetical Testing Ends`* 

<a id='EDA'></a>
## Exploratory Data Analysis

In [79]:
df.Points.quantile([.25,.50,.75,1])

0.25    699.25
0.50    772.00
0.75    806.00
1.00    876.00
Name: Points, dtype: float64

In [80]:
df.Points.describe()

count     12.000000
mean     765.583333
std       67.849376
min      673.000000
25%      699.250000
50%      772.000000
75%      806.000000
max      876.000000
Name: Points, dtype: float64

In [81]:
df

Points  Rank    Team  Year  Points Scaled
0      876     1  Riders  2014      92.350068
1      789     2  Riders  2015      29.983446
2      863     2  Devils  2014      77.482564
3      673     3  Devils  2015    -148.379616
4      741     3   Kings  2014     -62.043234
5      812     4   kings  2015      65.348535
6      756     1   Kings  2016      70.710678
7      788     1   Kings  2017      70.710678
8      694     2  Riders  2016     -70.710678
9      701     4  Royals  2014    -107.789398
10     804     1  Royals  2015      53.047635
11     690     2  Riders  2017     -70.710678

In [82]:
popularity=pd.read_csv('./EDA-getting&cleaningdata/popularity.csv')

In [83]:
popularity.shares.describe() # max      843300.000000
#popularity.shares.quantile([.78]) #0.78    3100.0
print(popularity.shares.quantile([.1,.7,.8])) # beetween 70-80% the mean lay

AttributeError: 'DataFrame' object has no attribute 'shares'

In [ ]:
popularity[popularity.shares<=10800].shares.describe() #finding mean of the shares after removing outliers

In [ ]:
round(popularity[popularity.shares>10800].shares.count()/popularity.shares.count(),2)*100

##### Box Plot decoding
<img src="Boxplot_decoding.png" style="width: 600px;" alt="basic operations on datastructure" title="Box Plot Decoding" />

#### *Handling Categorical Data*

[categorical encoding](http://pbpython.com/categorical-encoding.html)

In [ ]:
cars=pd.read_csv('./EDA-getting&cleaningdata/CarPrice_Assignment.csv',encoding='iso-8859-1')

In [ ]:
cars_dtype_obj=cars.select_dtypes(include=['object'])
cars_dtype_obj[cars_dtype_obj.isnull().any(axis=1)]
cars_dtype_obj.dtypes

> ##### `FIND & Replace` finding value counts and using `replace` i.e. dataframe.replace(to-replace, value, inplace) ` some more parameters`

In [ ]:
cars_dtype_obj.doornumber.value_counts()
cars_dtype_obj.cylindernumber.value_counts()
to_replace_dict={
    'cylindernumber':{'four':4,'six':6,'five':5,'eight':8,'two':2,'twelve':12,'three':3},
    'doornumber':{'four':4,'two':2}}
cars.replace(to_replace_dict,inplace=True)

> ##### `Label Encoding` doing label encoding using `astype and cat.codes` 

In [ ]:
# FINDING number of unique values in columns
print(cars_dtype_obj.groupby('carbody')['CarName'].count())
pd.crosstab(cars_dtype_obj.carbody,cars_dtype_obj.CarName,margins=True)['All']

In [ ]:
cars_dtype_obj['carbody']=cars_dtype_obj['carbody'].astype('category')
cars_dtype_obj.dtypes
        # CarName             object
        # fueltype            object
        # aspiration          object
        # carbody           category
cars_dtype_obj['carbody']=cars_dtype_obj['carbody'].cat.codes
        # 0      0
        # 1      0
        # 2      2
        # 3      3
        # 4      3
        # 5      3

> ##### `One Hot Encoding` doing label encoding using `pd.get_dummies` 

In [ ]:
#pd.crosstab(cars_dtype_obj.enginelocation,cars_dtype_obj.CarName,margins=True)['All']
pd.get_dummies(cars_dtype_obj, columns=["enginelocation", "drivewheel"], prefix=["engine", "drive"]).head()

> ##### `Custom Binary Encoding` doing label encoding using `np.where` 

In [ ]:
#cars_dtype_obj["enginetype"] = np.where(cars_dtype_obj["enginetype"].str.contains("ohc"), 1, other=0)
np.where(cars_dtype_obj["enginetype"].str.contains("ohc"), 1, 0)

In [ ]:
eda_mh=pd.read_csv('./EDA-getting&cleaningdata/EDA_nas.csv',encoding='iso-8859-1')

In [ ]:
eda_mh.head()

In [ ]:
#Impact of Watch.tv on science marks
groupped=eda_mh.groupby('Watch.TV')

In [ ]:
eda_mh.dropna(axis=0,subset=['Science..']).groupby('Watch.TV')['Science..'].mean()

In [ ]:
# What is the impact of the father’s education on the student’s Maths marks?
# Students whose fathers have a degree and above get better marks on an average
eda_mh.groupby('Father.edu')['Maths..'].mean()

In [ ]:
# Students who play games once a week score high in Reading on an average
# Feedback : Students who play games once a week score 59.62% average marks in reading.
eda_mh.groupby('Play.games')['Reading..'].mean()

In [ ]:
gold_silver=pd.read_csv('./EDA-getting&cleaningdata/EDA_Gold_Silver_prices.csv')
#gold_silver[['SilverPrice','GoldPrice']].corr()

In [ ]:
gc_cp=gold_silver.copy()
gc_cp['year']=gc_cp.Month.apply(lambda x: datetime.datetime.strptime(x,'%b-%y').year)
# datetime.datetime.strptime(gold_silver.Month[0],'%b-%y').day

In [ ]:
# Bivariate Analysis
# What is the correlation in Gold and Silver prices for the years 2008(nearest two decimal places )?
gc_cp[gc_cp.year==2008].iloc[:,[1,2]].corr() # .01 %

In [ ]:
import datetime
gold_silver['Month']=pd.to_datetime(gold_silver['Month'],errors='coerce')

In [ ]:
gold_silver['Year']=gold_silver['Month'].apply(lambda x: x.year)

> EDA Important links
 - https://www.kaggle.com/etakla/exploring-the-dataset-bivariate-analysis 
 - https://www.digitalocean.com/community/tutorials/working-with-data-using-pandas-and-python-3 
 - https://www.analyticsvidhya.com/blog/2016/01/12-pandas-techniques-python-data-manipulation/ 
 - https://machinelearningmastery.com/quick-and-dirty-data-analysis-with-pandas/ 
 - https://www.orchardplatform.com/blog/2014522credit-variables-explained-number-of-open-accounts/ 
 - http://p2plendingexpert.com/credit-analysis-number-of-open-trade-lines/ 
 - https://www.google.com/search?q=The+total+number+of+credit+lines+currently+in+the+borrower%27s+credit+file&ie=utf-8&oe=utf-8&client=firefox-b-ab 
 - https://www.youtube.com/watch?v=9BioRu6LRLQ 


###### `EDA Finished`

#### Getting & Cleaning DATA

In [ ]:
import pymysql

# create a connection object 'conn'
conn = pymysql.connect(host="localhost", # your host, localhost for your local machine
                     user="root", # your username, usually "root" for localhost
                      passwd="yourpassword", # your password
                      db="world") # name of the data base; world comes inbuilt with mysql

# create a cursor object c
c = conn.cursor()

# execute a query using c.execute
c.execute("select * from city;")

# getting the first row of data as a tuple
all_rows = c.fetchall()

# to get only the first row, use c.fetchone() instead

In [ ]:
import requests, bs4

# getting HTML from the Google Play web page
url = "https://play.google.com/store/apps/details?id=com.facebook.orca&hl=en"
req = requests.get(url)

# create a bs4 object
# To avoid warnings, provide "html5lib" explicitly
soup = bs4.BeautifulSoup(req.text, "html5lib")

In [ ]:
# getting all the text inside class = "review-body"
reviews = soup.select('.review-body')
print(type(reviews))
print(len(reviews))
print("\n")

# printing an element of the reviews list
print(reviews)

In [ ]:
# Practice problem: Scraping amazon.in to get shoe price data 
import pprint

url = "https://www.amazon.in/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=sport+shoes"
req = requests.get(url)

# create a bs4 object
# To avoid warnings, provide "html5lib" explicitly
soup = bs4.BeautifulSoup(req.text, "html5lib")

# get shoe names
# shoe_data = soup.select('.a-size-medium')
# shoe_data = soup.select('.a-size-small.a-link-normal.a-text-normal')
# print(len(shoe_data))
# print(pprint.pprint(shoe_data))

# get shoe prices
shoe_prices = soup.select('.a-price-whole')
print(len(shoe_prices))
pprint.pprint(shoe_prices)

In [ ]:
import numpy as np
import pandas as pd

# Need requests to connect to the URL, json to convert JSON to dict
import requests, json
import pprint

# joining words in the address by a "+"
add = "UpGrad, Nishuvi building, Anne Besant Road, Worli, Mumbai"
split_address = add.split(" ")
address = "+".join(split_address)
print(address)

In [ ]:
api_key = "AIzaSyBXrK8md7uaOcpRpaluEGZAtdXS4pcI5xo"

url = "https://maps.googleapis.com/maps/api/geocode/json?address={0}&key={1}".format(address, api_key)
r = requests.get(url)

# The r.text attribute contains the text in the response object
print(type(r.text))
print(r.text)

In [ ]:
# converting the json object to a dict using json.loads()
r_dict = json.loads(r.text)

# the pretty printing library pprint makes it easy to read large dictionaries
pprint.pprint(r_dict)

In [ ]:
#conda install -c conda-forge pypdf2
import PyPDF2

# reading the pdf file
pdf_object = open('./EDA-getting&cleaningdata/animal_farm.pdf', 'rb')
pdf_reader = PyPDF2.PdfFileReader(pdf_object)

# Number of pages in the PDF file
print(pdf_reader.numPages)

# get a certain page's text
page_object = pdf_reader.getPage(5)

# Extract text from the page_object
print(page_object.extractText())

##### Handling Missing Values

In [ ]:
df=pd.read_csv('./EDA-getting&cleaningdata/melbourne.csv',sep=',')

In [ ]:
df.head()

In [ ]:
df.isnull().sum() # Column wise null estimation default axis=0 i.e. column
round(df.isnull().sum()/len(df.index),2)*100
#df.isnull().sum(axis=1) # Row wise null check axis=1

In [ ]:
#df.isnull().all(axis=1).value_counts()
len(df[df.isnull().sum(axis=1)>5].index)

#dropping rows with more than 5 missing values
df=df[df.isnull().sum(axis=1)<=5]

In [ ]:
len(df[df.isnull().sum(axis=1)>5].index)

In [ ]:
#len(df['Price'].isnull())
len(np.isnan(df['Price']))
#dropping na rows in proce
df.shape
df=df[~np.isnan(df['Price'])]

In [ ]:
df.loc[np.isnan(df['Lattitude']), ['Lattitude']]= df['Lattitude'].mean()

In [ ]:
df['Car']=df['Car'].astype('category')
#df['Car'].mean() #car cannont have mean 1.6155195681511472

In [ ]:
df['Bathroom']=df['Bathroom'].astype('category')

In [ ]:
df.loc[pd.isnull(df['Bathroom']),['Bathroom']]=1 #impuetinng null with 1

## Wide to Long Format: ```pd.melt()```

In [158]:
wide_df=pd.read_csv('./EDA-getting&cleaningdata/wide.csv')

In [159]:
wide_df.head()

Firstname Lastname  Age  Current Balance  Saving Balance  Deposit Balance
0     Harsh    Goyal   50             4000           56000          15000.0
1     Rahul    Anand   64            35000           45000              NaN
2     Sonam    Gupta   25            10000           70000              NaN

To convert this into a long format, we can use the ```pd.melt()``` function. You need to identify two types of variables and provide them as arguments to ```pd.melt()```:
1. *Identifier variables*: Columns used to identify a unique record (Firstname, Lastname and Age identify a unique person)
2. *Value variables*: Column(s) that are to be *melted* into a single column (Current, Saving and Deposit Balances) 

For e.g., in the above dataframe, the ```id_vars``` are ```Firstname, Lastname``` and ```Age```, while the other three columns are to be *melted into a single one*. 

The basic syntax for *melting* value variables is as follows: 
```pd.melt(df, id_vars, value_vars)```.

In [160]:
long_df = pd.melt(wide_df, 
        id_vars=['Firstname', 'Lastname', 'Age'], 
        value_vars=['Current Balance', 'Saving Balance', 'Deposit Balance'])
# renaming the newly created columns
long_df = long_df.rename(columns={'variable': 'Account Type', 'value': 'Balance'})
long_df

Firstname Lastname  Age     Account Type  Balance
0     Harsh    Goyal   50  Current Balance   4000.0
1     Rahul    Anand   64  Current Balance  35000.0
2     Sonam    Gupta   25  Current Balance  10000.0
3     Harsh    Goyal   50   Saving Balance  56000.0
4     Rahul    Anand   64   Saving Balance  45000.0
5     Sonam    Gupta   25   Saving Balance  70000.0
6     Harsh    Goyal   50  Deposit Balance  15000.0
7     Rahul    Anand   64  Deposit Balance      NaN
8     Sonam    Gupta   25  Deposit Balance      NaN

## Long to Wide Format: ```pd.pivot_table()```


Alternatively, you sometimes need to convert long dataframes into wide ones. The  ```pd.pivot_table()``` method can be used to do that.

Here is the long version of the dataframe.

In [161]:
long_df = pd.read_csv("./EDA-getting&cleaningdata/long.csv")
long_df

Firstname Lastname  Age Account Type  Balance
0     Harsh    Goyal   50      Current     4000
1     Harsh    Goyal   50      Deposit    15000
2     Harsh    Goyal   50       Saving    56000
3     Rahul    Anand   64      Current    35000
4     Rahul    Anand   64       Saving    45000
5     Sonam    Gupta   25      Current    10000
6     Sonam    Gupta   25       Saving    70000

In [ ]:
wide_df=long_df.pivot_table(index=['Firstname', 'Lastname', 'Age'],
                           columns='Account Type',
                           values='Balance')
wide_df

#### Additional Stuff to Read

Paper on tidy data by Hadley Wickham: http://vita.had.co.nz/papers/tidy-data.pdf


## Unsupervised Machine Learnning
> Principal Component Analysis (PCA) & Singular Value Decomposition (SVD)

##### **SVD**

In [ ]:
my_food=pd.read_csv('./svd/MyFoodRatings.csv')

In [ ]:
U,s,VT=np.linalg.svd(my_food.drop('Name',axis=1),full_matrices=True)
#U SCORES
#S WEIGHTS of THEMES
#VT LOADINGS

In [ ]:
U.shape, s.shape, VT.shape

In [ ]:
s[0:3] #Weights of themes
U[:9]

In [ ]:
np.diag(s[:3]), VT[:,:3]

In [ ]:
pd.DataFrame(VT[:3]).head()

In [ ]:
foodA5=pd.read_csv('./svd/FoodRatings_all_same_5.csv')
U,s,VT=np.linalg.svd(foodA5.drop('Name',axis=1),full_matrices=True)
s[:3]

In [ ]:
food345=pd.read_csv('./svd/FoodRatings_all_same_5_4_3.csv')
U,s,VT=np.linalg.svd(food345.drop('Name',axis=1),full_matrices=True)
s[:3]

##### *`SVD ENDS`*

### Polynomial Regression and Pipelining in Python

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
sample_feature=pd.DataFrame({'even':[2,4,6,8,10],'odd':[1,3,5,7,9]})
make_features=PolynomialFeatures(degree=2)

In [ ]:
sample_feature

In [ ]:
univariate=make_features.fit_transform(sample_feature[['even']])
bivariate=make_features.fit_transform(sample_feature)

In [ ]:
pd.DataFrame(univariate)

In [ ]:
pd.DataFrame(bivariate)