In [67]:
import numpy as np

## Initialization of numpy array
    * Direct initialization using np.array()
    * Converting list to an array np.array(list[])
    * Converting tuple to an array np.array(tuple())

In [68]:
list_1=[1,2,3,4,5]
tup_1=(6,7,8,9,'10')
np_la=np.array(list_1)
print("Type: {} value: {}".format(type(np_la),np_la))
np_ta=np.array(tup_1)
print("Type: {} value: {}".format(type(np_ta),np_ta))

Type: <class 'numpy.ndarray'> value: [1 2 3 4 5]
Type: <class 'numpy.ndarray'> value: ['6' '7' '8' '9' '10']


## Note 
### 1: As the data in ndarray is homogeneous, the data type of all the data is coverted to higher data type
    * Example 1: np_a1=np.array([1,2,3,4,5.09])  --------> all will be converted to float
    * Example 2: np_a1=np.array([1,2,3,4,'5'])  --------> all will be converted to string
    * Example 3: np_a1=np.array([1,2,3,4,False])  --------> all will be converted to number

In [69]:
np_a1=np.array([1,2,3,4,5.09])
np_a2=np.array([1,2,3,4,'5'])
np_a3=np.array([1,2,3,4,False])
np_a4=np.array([True,False,True,False,False])

In [70]:
print("Example 1- all float: ",np_a1)
print("Example 2- all string: ",np_a2)
print("Example 3- all number: ",np_a3)
print("Example 4- all boolean: ",np_a4)

Example 1- all float:  [ 1.    2.    3.    4.    5.09]
Example 2- all string:  ['1' '2' '3' '4' '5']
Example 3- all number:  [1 2 3 4 0]
Example 4- all boolean:  [ True False  True False False]


## Numpy 2-D array and terminology
    * In numpy dimensions are called **axes**
        In Numpy terminology, for 2-D arrays:
* ```axis = 0``` refers to the rows
* ```axis = 1``` refers to the columns

In [71]:
print("2 Dimension Array: Examples")
np_2d=np.array([[1,2,3],[4,5,6]])
print(np_2d)
print("Shape of array: ",np.shape(np_2d))
print("Size  of array: ",np.size(np_2d))
print("Average of row: ",np.average(np_2d,axis=1))
print("Average of column: ",np.average(np_2d,axis=0))
print("Average of 2D Array: ",np.average(np_2d)) #Default axis=None
print("mean 1st column: ",np.mean(np_2d[:,0])) 
print("median 1st column: ",np.median(np_2d[:,0])) 

2 Dimension Array: Examples
[[1 2 3]
 [4 5 6]]
Shape of array:  (2, 3)
Size  of array:  6
Average of row:  [ 2.  5.]
Average of column:  [ 2.5  3.5  4.5]
Average of 2D Array:  3.5
mean 1st column:  2.5
median 1st column:  2.5


### Custom dtype array

In [72]:
dtype=[('name',np.str_,16),('height',int)]
values=[('SaurabhJAIN',180),('Shilpa',168),('Meha',93)]
np_family=np.array(values, dtype=dtype)
print(np_family)
print(np.shape(np_family))
print(np.size(np_family))
print(np_family[1][1])
print(np.sort(np_family,order=['height','name']))

[('SaurabhJAIN', 180) ('Shilpa', 168) ('Meha',  93)]
(3,)
3
168
[('Meha',  93) ('Shilpa', 168) ('SaurabhJAIN', 180)]


In [73]:
#When we knwo the length of the array but not the step, we can use linspace.
# Below 25 elements are generated between 5-100 both inclusive
np_lin=np.linspace(5,100,25)
print(np_lin)
np_lin=np.linspace(5,100,25, dtype=int)
print(np_lin)

[   5.            8.95833333   12.91666667   16.875        20.83333333
   24.79166667   28.75         32.70833333   36.66666667   40.625
   44.58333333   48.54166667   52.5          56.45833333   60.41666667
   64.375        68.33333333   72.29166667   76.25         80.20833333
   84.16666667   88.125        92.08333333   96.04166667  100.        ]
[  5   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68  72
  76  80  84  88  92  96 100]


In [74]:
# Array of random numbers with shape (3,4), ideally generate numbers between 0-1
np_rnd=np.random.random([3,4])
print(np_rnd)

[[ 0.09959682  0.98574288  0.8694249   0.70567708]
 [ 0.09005567  0.26466961  0.75942357  0.10407324]
 [ 0.53711062  0.82407109  0.89309174  0.01311065]]


In [75]:
# np.arange is equivalent on range method. Below the max is not included and step size is used to increment

np_ar=np.arange(5,20,5)
print(np_ar)

[ 5 10 15]


## Inspecting content and structure of the array

In [76]:
rand_array=np.random.random([300,1000])
print(rand_array[1,])

[ 0.62004398  0.83818303  0.62855629  0.8598635   0.73383149  0.84129578
  0.63043513  0.23365858  0.67526109  0.99383942  0.68627872  0.14285083
  0.7632219   0.94620004  0.29695596  0.34090666  0.48511172  0.73785499
  0.38219634  0.41957189  0.26592396  0.94073925  0.14590022  0.42672541
  0.13288548  0.71996416  0.9845729   0.36214849  0.94338422  0.9232539
  0.12655484  0.62685242  0.81239964  0.49271614  0.4944642   0.49397365
  0.53983182  0.6510447   0.99161857  0.19577448  0.40852529  0.16589612
  0.40937108  0.84738776  0.30399415  0.48042548  0.37221221  0.77493754
  0.81497804  0.69467039  0.61427853  0.00829027  0.48207001  0.95470349
  0.50150928  0.1821147   0.11904775  0.4520664   0.08577068  0.7713533
  0.19514901  0.641435    0.87407803  0.41682367  0.69216698  0.54099305
  0.27034688  0.48283476  0.72236087  0.16934978  0.25714227  0.09937765
  0.35554111  0.13284078  0.29732536  0.10706869  0.2032048   0.48479434
  0.5266878   0.10429042  0.36818483  0.11737002  0.0

  0.56906888  0.86827038  0.53928249  0.46889176]


In [77]:
print(np.size(rand_array)) # ->>>> print(rand_array.size)
print(np.shape(rand_array)) # ->>>>> print(rand_array.shape)
print(rand_array.dtype)
print(rand_array.itemsize)
print(rand_array.ndim)

300000
(300, 1000)
float64
8
2


In [78]:
np_lin=np.linspace(5,100,25)
print(np_lin.ndim)
reshaped_np_lin=np_lin.reshape(5,5)
print(reshaped_np_lin.ndim)

1
2


In [79]:
dim_3_arr=np.arange(24).reshape(2,3,4)
dim_4_arr=np.arange(24).reshape(2,3,2,2)
print(dim_3_arr.ndim)
print(dim_4_arr.ndim)
print(dim_3_arr)
print(dim_4_arr)

3
4
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


## Subset, slice, indexing and iterating over arrays

In [80]:
D1_arr=np.linspace(1,10,10,dtype=int)
D2_arr=np.arange(9).reshape(3,3)
print(D1_arr)
print(D2_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [81]:
print(D1_arr[:]) # slice
print(D1_arr[[1,3,5]]) # slice
print(D1_arr[1::2]) #starting at index 1 printing even numbers (subset)
#Iterating
for i in D1_arr:
    print(i)

[ 1  2  3  4  5  6  7  8  9 10]
[2 4 6]
[ 2  4  6  8 10]
1
2
3
4
5
6
7
8
9
10


In [82]:
print(D2_arr[:])
print(D2_arr[1:3,1:3]) #-->>>> print(D2_arr[1:3,[1,2]])
print(D2_arr[:,(0,2)])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[4 5]
 [7 8]]
[[0 2]
 [3 5]
 [6 8]]


In [86]:
some_arr=np.arange(12).reshape(4,-1)
print(some_arr)
print(some_arr.T)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


## Vertical Stacking where columns of stacking elements should be same

In [92]:
D54_arr=np.arange(20).reshape(5,4)
D34_arr=np.arange(12).reshape(3,4)
D84_arr=np.vstack((D54_arr,D34_arr)) # Will be doing vertical stacking where columns need to be same size
print(D34_arr, " : dimesnion", D34_arr.ndim, " :Shape ", D34_arr.shape)
print(D54_arr, " : dimesnion", D54_arr.ndim, " :Shape ", D54_arr.shape)
print(D84_arr, " : dimesnion", D84_arr.ndim, " :Shape ", D84_arr.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]  : dimesnion 2  :Shape  (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]  : dimesnion 2  :Shape  (5, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]  : dimesnion 2  :Shape  (8, 4)


# Horizontal Stacking where rows of stacking elements should be same

In [94]:
D35_arr=np.arange(15).reshape(3,5)
D34_arr=np.arange(12).reshape(3,4)
D39_arr=np.hstack((D34_arr,D35_arr))
print(D34_arr, " : dimesnion", D34_arr.ndim, " :Shape ", D34_arr.shape)
print(D35_arr, " : dimesnion", D35_arr.ndim, " :Shape ", D35_arr.shape)
print(D39_arr, " : dimesnion", D39_arr.ndim, " :Shape ", D39_arr.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]  : dimesnion 2  :Shape  (3, 4)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]  : dimesnion 2  :Shape  (3, 5)
[[ 0  1  2  3  0  1  2  3  4]
 [ 4  5  6  7  5  6  7  8  9]
 [ 8  9 10 11 10 11 12 13 14]]  : dimesnion 2  :Shape  (3, 9)


In [102]:
a=np.arange(1,20)
print(type(a))
print(a)

a_list=[x/(1+x) for x in a]
print(a_list)

f=np.vectorize(lambda x: x/(1+x))
print(f(a))

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.5, 0.66666666666666663, 0.75, 0.80000000000000004, 0.83333333333333337, 0.8571428571428571, 0.875, 0.88888888888888884, 0.90000000000000002, 0.90909090909090906, 0.91666666666666663, 0.92307692307692313, 0.9285714285714286, 0.93333333333333335, 0.9375, 0.94117647058823528, 0.94444444444444442, 0.94736842105263153, 0.94999999999999996]
[ 0.5         0.66666667  0.75        0.8         0.83333333  0.85714286
  0.875       0.88888889  0.9         0.90909091  0.91666667  0.92307692
  0.92857143  0.93333333  0.9375      0.94117647  0.94444444  0.94736842
  0.95      ]


In [112]:
d2_arr=np.linspace(1,100,12, dtype=int).reshape(3,4)
print(d2_arr)
print(f(d2_arr))

d2_arr33=np.linspace(1,21,9, dtype=int).reshape(3,3)
d2_arr33_inv=np.linalg.inv(d2_arr33)
print(d2_arr33, "   :   ",d2_arr33_inv)
print(np.dot(d2_arr33,d2_arr33_inv))

[[  1  10  19  28]
 [ 37  46  55  64]
 [ 73  82  91 100]]
[[ 0.5         0.90909091  0.95        0.96551724]
 [ 0.97368421  0.9787234   0.98214286  0.98461538]
 [ 0.98648649  0.98795181  0.98913043  0.99009901]]
[[ 1  3  6]
 [ 8 11 13]
 [16 18 21]]    :    [[ 0.04       -0.6         0.36      ]
 [-0.53333333  1.         -0.46666667]
 [ 0.42666667 -0.4         0.17333333]]
[[  1.00000000e+00  -2.22044605e-16   0.00000000e+00]
 [  1.66533454e-16   1.00000000e+00  -4.44089210e-16]
 [ -2.77555756e-16  -1.11022302e-16   1.00000000e+00]]


In [120]:
mat=np.array([[1,2],[3,4]],dtype=int)
print(mat)
print(np.linalg.det(mat))
print(np.linalg.inv(mat))
print(mat*np.linalg.inv(mat)) #element wise multipication this is not equivalent to MATRIX multipication

print("MATRIX Mulitipication is done via np.dot(m1,m2)")
print(np.dot(mat,np.linalg.inv(mat)))
help(np.dot)

[[1 2]
 [3 4]]
-2.0
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   2. ]
 [ 4.5 -2. ]]
MATRIX Mulitipication is done via np.dot(m1,m2)
[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]
Help on built-in function dot in module numpy.core.multiarray:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays.
    
    For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
    arrays to inner product of vectors (without complex conjugation). For
    N dimensions it is a sum product over the last axis of `a` and
    the second-to-last of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : ndarray, optional
        Output argument. This must have the exact kind that would be returned
        if it was not used. In particular, it must have the right type, must be
        C-contiguous, and its dtype must be the dty